# Generated by Django 5.0.1 on 2024-02-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nums', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/%y/%m/%d')),
            ],
        ),
    ]
