# Generated by Django 5.0.1 on 2024-02-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lec',
            name='nums',
        ),
    ]
