# Generated by Django 4.1.13 on 2024-03-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0002_anyt_delete_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='anyt',
            new_name='Lec',
        ),
    ]
