# Generated by Django 5.0.1 on 2024-02-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0002_remove_lec_nums'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lec',
            table='imageupload',
        ),
    ]
