# Generated by Django 4.1.13 on 2024-03-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0003_rename_anyt_lec'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.FileField(upload_to='videos/%y/%m/%d')),
                ('catgory', models.CharField(choices=[], default=[], max_length=100)),
            ],
            options={
                'verbose_name': 'فيديوات المحاضرات',
            },
        ),
    ]
