# Generated by Django 5.0.1 on 2024-02-03 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0003_alter_lec_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lec',
            table=None,
        ),
    ]
