# Generated by Django 4.1.13 on 2024-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0004_lecvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecvideo',
            name='catgory',
            field=models.CharField(choices=[('الفقه', 'الفقه'), ('المنطق', 'المنطق'), ('السيرة', 'السيرة'), ('الاصول', 'الاصول')], default=[], max_length=100),
        ),
    ]
