# Generated by Django 5.0.1 on 2024-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0004_alter_lec_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='lecVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.FileField(upload_to='videos/%y/%m/%d')),
                ('catgory', models.BooleanField(verbose_name=['ar', 'en'])),
            ],
        ),
    ]
