# Generated by Django 5.0.1 on 2024-02-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0005_lecvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecvideo',
            name='catgory',
            field=models.BooleanField(),
        ),
    ]
