# Generated by Django 4.1.13 on 2024-03-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0005_alter_lecvideo_catgory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecvideo',
            name='catgory',
            field=models.CharField(choices=[('الفقه', 'الفقه'), ('المنطق', 'المنطق'), ('السيرة', 'السيرة'), ('الاصول', 'الاصول'), ('h', 'h')], default=[], max_length=100),
        ),
    ]
