# Generated by Django 5.0.1 on 2024-02-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0006_alter_lecvideo_catgory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lecVideo',
        ),
    ]
