# Generated by Django 5.0.1 on 2024-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0008_lecvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lec',
            options={'verbose_name': 'اقسام المحاضرات'},
        ),
        migrations.AlterModelOptions(
            name='lecvideo',
            options={'verbose_name': 'فيديوات المحاضرات'},
        ),
        migrations.AlterField(
            model_name='lecvideo',
            name='catgory',
            field=models.CharField(choices=[('الفقه', 'الفقه'), ('المنطق', 'المنطق'), ('الفلسفة', 'الفلسفة'), ('علم الكلام', 'علم الكلام'), ('السيرة', 'السيرة')], max_length=100),
        ),
    ]
