# Generated by Django 5.0.1 on 2024-02-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecsApp', '0010_alter_lec_image_alter_lecvideo_catgory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecvideo',
            name='catgory',
            field=models.CharField(choices=[('علم الكلام', 'علم الكلام'), ('الاصول', 'الاصول'), ('السيرة', 'السيرة'), ('الفلسفة', 'الفلسفة'), ('الفقه 1', 'الفقه 1'), ('المنطق', 'المنطق'), ('الحديث والرجال', 'الحديث والرجال'), ('التاريخ', 'التاريخ'), ('اختبار', 'اختبار')], default=('علم الكلام', 'علم الكلام'), max_length=100),
        ),
    ]
